colors.draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x2D2A2E"
foreground = "0xfff1f3"

[colors.normal]
black = "0x2c2525"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"

[colors.bright]
black = "0x72696a"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "MonoLisa"
style = "Bold"

[font.bold_italic]
family = "MonoLisa"
style = "Bold Italic"

[font.italic]
family = "MonoLisa"
style = "Italic"

[font.normal]
family = "MonoLisa"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 100000
multiplier = 3

[terminal.shell]
program = "/usr/bin/fish"

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.8

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
