theme = "kanagawa"

[editor]
shell = ["pwsh", "-c"]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
max-depth = 5

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[keys.normal]
"0" = "goto_line_start"
"+" = "goto_line_end"
"A-w" = ":write"
"x" = "delete_selection"
"D" = "kill_to_line_end"
"V" = "extend_line_below"

[keys.select]
"o" = "flip_selections"
"0" = "goto_line_start"
"+" = "goto_line_end"
